import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modules = process.env.RUNTIME_NODE_MODULES;
if (!modules) throw new Error('Set RUNTIME_NODE_MODULES to the bundled runtime node_modules directory');
const require = createRequire(path.join(modules, '__resolve__.cjs'));
const {Presentation, PresentationFile} = await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
await fs.mkdir(path.join(root, '.build/slides'), {recursive:true});
process.chdir(path.join(root, '.build/slides'));
const skill=process.env.PRESENTATIONS_SKILL_DIR || '/Users/arshiadang/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const runtime=process.env.RUNTIME_DEPENDENCIES || '/Users/arshiadang/.cache/codex-runtimes/codex-primary-runtime/dependencies';
const {resolvePresentationFont,applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
const font=resolvePresentationFont();
const d=JSON.parse(await fs.readFile('data.json','utf8'), (key,value)=>typeof value==='number'?Number(value.toFixed(8)):value);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const ink='#16343B', teal='#237B77', orange='#D18B29', muted='#576B70';
function text(s,value,x,y,w,h,size=28,color=ink,bold=false){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=value;t.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return t;}
function slide(title,notes=''){const s=p.slides.add();s.background.fill='#FBFAF6';text(s,title,65,40,1150,120,42,ink,true);text(s,String(p.slides.items.length).padStart(2,'0'),1165,665,50,30,18,muted);s.speakerNotes.textFrame.setText(notes);return s;}
function table(s,values,y=180,widths=[500,300,300]){const t=s.tables.add({rows:values.length,columns:values[0].length,left:70,top:y,width:1140,height:values.length*68,columnWidths:widths,values});for(let r=0;r<values.length;r++)for(let c=0;c<values[0].length;c++){const cell=t.getCell(r,c);cell.fill=r===0?ink:(r%2?'#FFFFFF':'#F0F3EF');cell.text.style={typeface:font,fontSize:25,color:r===0?'#FFFFFF':ink,bold:r===0};}return t;}
function line(s,categories,series,left,top,width,height,title,ylabel){const chart=s.charts.add('line',{position:{left,top,width,height},title,titleTextStyle:{typeface:font,fontSize:25,fill:ink},categories,series:series.map((a,i)=>({...a,line:{fill:[teal,orange,'#7D6CA7'][i],width:3}})),lineOptions:{smooth:false},hasLegend:true,legend:{position:'bottom',textStyle:{typeface:font,fontSize:19}},xAxis:{title:'K',textStyle:{typeface:font,fontSize:17}},yAxis:{title:ylabel,min:0,max:1,numberFormatCode:'0.0',textStyle:{typeface:font,fontSize:17},majorGridlines:{fill:'#D8DFDC',width:1}}});applyPresentationChartFont(chart,{fontFamily:font});return chart;}
let s=slide('Heatwave severity with KNN','Source: user-provided Final Design Spec revision 2. Dataset and all result tables: notebooks/analysis.ipynb.');
text(s,'Maharashtra · March–June · 2015–2025',70,180,1120,65,35,teal);
text(s,'Same-day classification using real IMD observations',70,278,1060,100,46,ink,true);
text(s,'Machine Learning (216H13C501)\nExp8 extension · KJS-CES-01',70,485,1050,110,28,muted);
s=slide('Data and climatological normal','IMD: https://www.imdpune.gov.in/cmpg/Griddata/Max_1_Bin.html . geoBoundaries source/license: data/boundaries/source.json. IMD files 1991–2025 were downloaded and byte-count validated.');
text(s,'26 grid centres',70,170,650,75,56,teal,true);
text(s,'1° IMD Tmax grid, clipped by Maharashtra cell centres.\n34,892 March–June modelling observations.',70,265,1120,120,30);
text(s,'Normal: pooled ±7-day window across 1991–2014.\nExclude 29 February and use a fixed 365-day calendar.\nThis normal differs from IMD’s official normal.',70,430,1120,165,30);
s=slide('Operational Heatwave Severity Rules\n(Project Approximation)','Source: approved design revision 2, section 6.3. The rules have not been verified against published IMD criteria. Applied per cell/day without station-level persistence.');
table(s,[['Condition','Heatwave','Severe'],['Departure (Tmax meets base)','≥4.5°C','≥6.5°C'],['Normal ≥40°C','Tmax ≥45°C','Tmax ≥47°C']],205,[550,280,310]);
text(s,'Base Tmax: plains 40°C, coastal 37°C, hilly 30°C.\nBelow the base: Normal. Higher applicable severity wins.',70,455,1140,100,28);
text(s,'Own geographic region lookup, without terrain validation.\nCell/day rules omit station-level persistence criteria.',70,573,1140,70,24,muted);
s=slide('The Severe class has no observations','Source: reports/results/class_counts.csv. The model cannot produce a class absent from its fitted training labels. Macro-F1 uses all three requested labels.');
table(s,[['Severity','Train 2015–2022','Test 2023–2025'],['Normal','25,234','9,495'],['Heatwave','142','21'],['Severe Heatwave','0','0']],180,[510,340,290]);
text(s,'Severe recall is unavailable. The trained KNN cannot predict Severe.\nFixed three-class macro-F1 has a maximum of 2/3 for these data.',70,510,1140,115,29,'#A34538',true);
s=slide('One pipeline for analysis and demo','Source: heatwave/pipeline.py and heatwave/model.py. StandardScaler is refit within each leave-one-year-out training fold.');
text(s,'Raw date, location, region, Tmax and normal Tmax',70,165,1130,65,31,teal,true);
text(s,'FeatureBuilder recomputes departure and seasonal sine/cosine.\nStandardScaler fits six numeric features inside each fold.\nOneHotEncoder handles the project region type.\nKNN assigns the same-day severity.',70,260,1130,210,30);
text(s,'Eight year folds, 52 configurations, macro-F1 selection.\nK = 1, 3, …, 25; Euclidean or Manhattan; uniform or distance.',70,520,1130,100,27,muted);
s=slide('K sensitivity: Euclidean, uniform voting','Source: reports/results/grid_search.csv. Curves show mean train and validation scores across leave-one-year-out folds. Full notebook plots also display fold standard deviation.');
const cats=d.curves.map(r=>String(r.param_knn__n_neighbors));
line(s,cats,[{name:'Train',values:d.curves.map(r=>r.mean_train_accuracy)},{name:'Cross-validation',values:d.curves.map(r=>r.mean_test_accuracy)}],55,160,575,400,'Accuracy','Accuracy');
line(s,cats,[{name:'Train',values:d.curves.map(r=>r.mean_train_macro_f1)},{name:'Cross-validation',values:d.curves.map(r=>r.mean_test_macro_f1)}],650,160,575,400,'Macro-F1','Macro-F1');
text(s,'Selected: K=1, Euclidean distance, uniform voting.\nUniform voting makes the larger-K training trade-off visible.',70,585,1130,75,27,muted);
s=slide('Held-out performance','Sources: reports/results/metrics.csv and classification_report.csv. Test years: 2023–2025. Majority baseline uses the most common training class.');
table(s,[['Metric','KNN','Majority baseline'],['Macro-F1 (three classes)','0.5999','0.3330'],['Heatwave recall','16/21 = 76.2%','0/21 = 0%'],['Severe recall','N/A, zero support','N/A, zero support'],['Accuracy','99.92%','99.78%']],160,[500,320,320]);
text(s,'Heatwave precision: 84.2%. Heatwave F1: 0.800.\nAccuracy alone hides the rare-class errors.',70,550,1140,85,28,teal,true);
s=slide('Reading noise changes both inputs and labels','Source: reports/results/noise_mean.csv. Five seeds: 11,23,37,51,71. Only Tmax is perturbed. Normal stays fixed. Curves use the selected K, metric and weighting. Full notebook covers all 13 K values.');
const targets=['Original labels','Recomputed rules','Rules vs original'];
const noise=d.noise.filter(r=>r.k===1);
const chart=s.charts.add('line',{position:{left:65,top:155,width:740,height:420},categories:['0.5','1','2'],series:targets.map((name,i)=>({name,values:[.5,1,2].map(sig=>noise.find(r=>r.sigma===sig&&r.comparison===name).macro_f1),line:{fill:[teal,orange,'#7D6CA7'][i],width:3}})),lineOptions:{smooth:false},hasLegend:true,legend:{position:'bottom',textStyle:{typeface:font,fontSize:19}},xAxis:{title:'Noise σ (°C)',textStyle:{typeface:font,fontSize:20}},yAxis:{title:'Macro-F1',min:0,max:1,numberFormatCode:'0.0',textStyle:{typeface:font,fontSize:20}}});applyPresentationChartFont(chart,{fontFamily:font});
text(s,'Five fixed seeds\n\nNormal temperature\nstays unchanged.\n\nDeparture and rules\nare recomputed.',845,190,355,340,28);
text(s,'Original-label Severe recall remains N/A. If noisy rules create Severe cases,\nthis KNN still has no Severe neighbours to learn from.',70,590,1140,75,26,muted);
s=slide('Demonstration and interpretation','Sources: app.py, heatwave/demo.py, reports/report.md. User-provided design requires explicit disclosure that labels derive from inputs.');
text(s,'The app compares KNN with the project rule label.',70,170,1130,80,34,teal,true);
text(s,'Enter Tmax, normal Tmax, a March–June date and a Maharashtra location.\nInspect departure, nearest-cell region and neighbour vote shares.\nVote shares are not calibrated probabilities.',70,275,1130,155,29);
text(s,'Labels come from two model inputs. This evaluates approximation of\noperational decision boundaries, not independent forecasting capability.',70,485,1130,115,30,ink,true);
s=slide('Limits and team review','Sources: reports/report.md and approved design revision 2. Retaining the locked rules and split is deliberate. Widening scope requires a documented protocol revision.');
text(s,'Three-class learning remains unsupported by these data.',70,165,1130,105,40,'#A34538',true);
text(s,'Zero Severe examples and only 21 Heatwave test examples limit conclusions.\nThe coarse grid smooths local extremes.\nThe coastal/hilly/plains assignment is an unvalidated location proxy.\nSpatial and temporal correlation reduce independent evidence.',70,305,1130,215,29);
text(s,'Revisit class feasibility with the team before submission.\nKeep any change to period, resolution or rules explicit and reproducible.',70,565,1130,80,27,teal,true);
await fs.mkdir('previews',{recursive:true});
await (await PresentationFile.exportPptx(p)).save('candidate.pptx');
for(let i=0;i<p.slides.items.length;i++){const img=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(`previews/slide-${i+1}.png`,new Uint8Array(await img.arrayBuffer()));}
const result=await finalizePresentation({workspaceDir:root,candidatePath:path.join(root,'.build/slides/candidate.pptx'),finalPath:path.join(root,'reports/slides/heatwave_knn.pptx'),pythonExecutable:path.join(runtime,'python/bin/python3'),integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit','--require-native-table-slide','3','--require-native-table-slide','4','--require-native-table-slide','7'],fontPolicy:{basis:'design',families:[font]},requiredNativeTableOwnerSlides:[3,4,7],requiredNativeChartOwnerSlides:[6,8],materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(root,'.build/slides/validation.json')});
console.log(result);
